version: '3.2'
services:
  jupyter:
    image: jupyter/all-spark-notebook:python-3.10.6
    ports:
      - "40400:4040"
      - "8890:8888"
    environment:
      - JUPYTER_TOKEN=pwd
    volumes:
      # set this path to the (absolute) path on your computer
      # - /Absolute/Path/To/Where/Your/Notebook/Files/Will/Be/Saved:/home/jovyan/work
      - ./work:/home/jovyan/project
      - python-libraries:/opt/conda/lib/python3.10/site-packages
    # the following volumes daclaration is used only for named anonymous storages
    #  - jupyter-data:/home/jovyan/work
    networks:
      - dsi-project
    container_name: jupyter-container

# to be used for named anonymous storages
#  jupyter-data: {}
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dsi-project
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dsi-project
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DSIholiday
      - POSTGRES_DB=dsi_postgres
    networks:
      - dsi-project
volumes:
  python-libraries:
networks:
  dsi-project:
    driver: bridge

version: '3'
services:
  jupyter:
    image: jupyter/all-spark-notebook:python-3.10.6
    ports:
      - "40400:4040"
      - "8890:8888"
    environment:
      - JUPYTER_TOKEN=dsi
    volumes:
      # set this path to the (absolute) path on your computer
      # - /Absolute/Path/To/Where/Your/Notebook/Files/Will/Be/Saved:/home/jovyan/work
      - ./work:/home/jovyan/work
      - python-libraries:/opt/conda/lib/python3.10/site-packages
    # the following volumes daclaration is used only for named anonymous storages
    #  - jupyter-data:/home/jovyan/work
    networks:
      - jupyter
    container_name: jupyter-container
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - jupyter
    container_name: zookeeper-container
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka-container:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - jupyter
    container_name: kafka-container
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DSIholiday
      - POSTGRES_DB=dsi_postgres
    networks:
      - jupyter
    
# to be used for named anonymous storages
volumes:
  python-libraries:
#  jupyter-data: {}

networks:
  jupyter:
    name: jupyter-network